kcptun-client:
  image: xjdata/kcptun-client
  ports:
    - "8388/udp"
  environment:
    - KEY=kcptun-server-set-password
    - LISTEN_PORT=8388
    - TARGET_ADDR=you-kcptun-serer-domain-or-ip
    - TARGET_PORT=kcptun-server-set-port
  restart: always

ss-client:
  image: xjdata/shadowsocks-client
  ports:
    - "1081:8388/tcp"
    - "1081:8388/udp"
  environment:
    - SERVER_ADDR=kcptun-client
    - SERVER_PORT=8388
    - PASSWORD=shadowsocks-server-set-password
    - METHOD=aes-256-cfb
  links:
    - kcptun-client
  restart: always
